Reduce computational time of AWS megatest
nf-core/phaseimpute pull request #158
Opened 2024-11-10 18:51 UTC by LouisLeNezet

This PR change the features tested in the fulltest config on AWS to reduce computational cost.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/phaseimpute/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/phaseimpute _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core pipelines lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-11-10 18:56 UTC, LouisLeNezet commented
Whenever we have merged the chunk_model update I will launch the updated fulltest on my cluster.

2024-11-17 17:06 UTC, atrigila requested changes
Always impressed by the amount of work you put on these contributions - much appreciated! :)

I noticed several distinct topics being addressed here. To make reviews faster and keep the changelog and file history cleaner, it would help if each of these topics were split into separate PRs. This also makes it easier to track changes and ensure each update is well-documented. Here are the main topics I see in this PR and that I tried to provide feedback on:

1. Reducing computational cost in fulltest configuration on AWS: This is the primary focus, and it's a great enhancement. You said previously that you have evidence that these new changes make the pipeline full test work, so I believe this is ready. 
2. `VCF_SPLIT_BCFTOOLS` edge case fix: Since this is a specific edge case fix, a separate PR would be ideal. In this particular case I see a great benefit of having this particular subworkflow in nf-core/modules, as it allows the community to review and provide feedback on these changes, speeding up the review process and then only making this a simple update in the pipeline :)
3. Snapshot file updates and output file prefix changes: I understand that there have been changes in how files are named and therefore the snapshots, but it would be nice if this could have been something separate to provide context on why these prefixes were adjusted.
4. "Lenient mode" addition: This appears to be a new feature but I couldn't find any reference in your PR description talking about this, could you explain its purpose and the scenarios where it would be useful?
5. Minor corrections in the changelog and punctuation fixes: These small adjustments (like punctuation or formatting) would be best suited for a separate "cleanup" PR  but they are OK.

2024-11-17 17:25 UTC, LouisLeNezet commented on conf/modules.config
> +        cache = "lenient"
The `lenient` mode enable to cache the file without checking for the timestamp of the last modification of the files.
This enable us to resume even with the fasta index that was recomputed some times.
More infos in https://www.nextflow.io/docs/latest/cache-and-resume.html

2024-11-17 17:27 UTC, LouisLeNezet commented
I'm sorry that this PR have too much files changed.
It's just that when I do some debugging there is some small changed that needs to be adressed and they pile up quite quickly.
I'll try to split it.

2024-11-17 17:29 UTC, LouisLeNezet commented on nextflow.config
This change allow to add change in the `test<all,glimpse2,quilt,...>.config` files that would be otherwise overwritten by the default if this was include afterwards.

2024-11-17 17:31 UTC, LouisLeNezet commented on conf/test.config
> +        memory: '2.GB',
Sorry I thought it was 2.
I will update it to 4 in this case.

2024-11-17 17:37 UTC, LouisLeNezet commented on assets/multiqc_config.yml
> +    pattern: "\\.batch[0-9]+"
There is batch file processed in the statistic. The aim to remove this pattern was to clean up a bit the name of the sample in the multiqc output html.
What could be done would be to allow the grouping of the samples by batch in the multiqc output (enable by the last multiqc version). But I think this should be done outside this PR.

2024-11-17 17:53 UTC, LouisLeNezet commented on workflows/phaseimpute/tests/main.nf.test.snap
> +                "simulation/NA20359.depth_1x.bam.csi",
This will be done in a separate PR

2024-11-17 17:53 UTC, LouisLeNezet commented on workflows/phaseimpute/tests/main.nf.test.snap
> +                "validation/stats/NA20359_SNP.txt"
This will be done in a separate PR

2024-11-17 18:34 UTC, LouisLeNezet reviewed
Ready for changes

2024-11-17 18:43 UTC, LouisLeNezet commented on conf/steps/validation.config
> +            path: { "${params.outdir}/validation/stats" },
Done in separate PR.

2024-11-17 18:45 UTC, LouisLeNezet commented on conf/steps/panel_prep.config
> +        ext.args   = "--window-size 4000000"
The value of this parameter is empirical and might need to be optimized depending on the cluster and specie studied.
This value seems to be a good compromised : enough parrelization and not to small to crash GLIMPSE2_CHUNKS.

2024-11-17 18:52 UTC, LouisLeNezet commented on conf/steps/panel_prep.config
> +        ext.args   = "--window-size 4000000"
Done

2024-11-23 20:20 UTC, LouisLeNezet commented
Hi @atrigila this PR is now ready !

2024-11-24 18:50 UTC, atrigila approved these changes

2024-11-24 18:50 UTC, atrigila commented on conf/test_all.config
> +        memory: '4.GB',
I think it can handle up to 15GB

2024-11-24 19:25 UTC, merged